docs/decisions/0001-new-designer-service.rst

In keeping with our new ADR goals, this documents why we created this
new IDA and some details of how it will be used.

Add new ADR for what Designer is

---

designer/settings/base.py

App was accidentally added prematurely and is breaking the build

Remove pages app

---

designer/settings/utils.py

This is what happens when you trust your "simple" change.

Fix missing imports

---

designer/apps/core/views.py
designer/apps/pages/models.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

Force a hierarchy of `/<index_page>/<program_page>/`

Force hierarchy when creating pages

---

designer/settings/base.py
designer/urls.py

Everything can be done via the /cms

Disable the /admin view

---

openedx.yaml

Update OEP-2 tags. 
[PROD-440](https://openedx.atlassian.net/browse/PROD-440) / [PROD-1012](https://openedx.atlassian.net/browse/PROD-1012)

update to oep-2

---

designer/apps/branding/models.py
designer/apps/core/tests/test_views.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/production.txt
requirements/quality.in
requirements/quality.txt
requirements/test.in
requirements/test.txt

The latest version of the `edx-drf-extensions` package (2.4.5) has a security fix that we were asked to bring into `portal-designer`.

Upgrade packages, specifically edx-drf-extensions

---

designer/settings/base.py
provision-designer.sh

https://openedx.atlassian.net/browse/BOM-1225

Remove oidc settings and token generation.

---

designer/settings/base.py
designer/settings/local.py

[BOM-1337](https://openedx.atlassian.net/browse/BOM-1337)

BOM-1337: Replaced MIDDLEWARE_CLASSES with MIDDLEWARE

---

designer/apps/api/urls.py
designer/settings/base.py
designer/urls.py
requirements/base.in
requirements/base.txt
requirements/dev.in
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/github.in
requirements/production.txt
requirements/quality.txt
requirements/test.txt

Relevant JIRA Links:
[https://openedx.atlassian.net/browse/BOM-1383](https://openedx.atlassian.net/browse/BOM-1383)
[https://openedx.atlassian.net/browse/BOM-1385](https://openedx.atlassian.net/browse/BOM-1385)
[https://openedx.atlassian.net/browse/BOM-1377](https://openedx.atlassian.net/browse/BOM-1377)

Upgraded django-debug-toolbar and social-auth-app-django and Fixed django20 warning

---

.travis.yml
Makefile
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/production.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
tox.ini

Related JIRA : [https://openedx.atlassian.net/browse/BOM-1386](https://openedx.atlassian.net/browse/BOM-1386)

BOM-1386 : Multiple django versions workers added to travis

---

designer/settings/base.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt

**Issue:** [BOm-1410](https://openedx.atlassian.net/browse/BOM-1410)
- Ran `make upgrade` to downgrade the `drf-jwt` version to `1.14.0`.

Downgrading drf-jwt version to 1.14.0

---

.travis.yml
tox.ini

**Issue:** [BOM-1528](https://openedx.atlassian.net/browse/BOM-1528)
- Updated `Travis.yml` to include `python3.8` support.
- Updated `tox.ini` to include `python3.8` and `django3.0`.

Updated python and django versions in Travis & Tox

---

designer/apps/core/signals.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/production.txt
requirements/quality.in
requirements/quality.txt
requirements/test.txt

https://openedx.atlassian.net/browse/BOM-1647

BOM-1647 : Remove caniusepython3

---

docker-compose.yml

Bump mysql version from 5.6 to 5.7
Tested locally, all changes that were made before bump to 5.6 appeared after version was upgraded.

Upgrade to mysql 5.7

---

Dockerfile

Relevant JIRA issue here: https://openedx.atlassian.net/browse/BOM-2004

updated the Dockerfile to use python 3.8

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt

Its already using wagtail==2.11.3 which is latest version. 
https://docs.wagtail.io/en/stable/releases/2.11.html#

Make upgrade job

---

Makefile
requirements/base.txt
requirements/common_constraints.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt

- Resolved all pyjwt version 2.0 breaking changes
- Overrriden a few global constraints by downloading the common constraint file
- Upgraded edx-drf-extensions to the latest version
- Upgraded edx-auth-backends to the latest version
For more info about pyjwt changes: https://pyjwt.readthedocs.io/en/stable/changelog.html
JIRA: [BOM-2759](https://openedx.atlassian.net/browse/BOM-2759)

feat: upgrade pyjwt to 2.1.0

---

tox.ini

fix: adding missing django32 in tox.

fix: adding missing django32 in tox.

---

Dockerfile
Makefile
designer/docker_gunicorn_configuration.py
designer/settings/utils.py
docker-compose.yml
provision-designer.sh

The purpose of this PR is to update the Dockerfile for the portal designer so we use this for portal designer k8s deployment.
Made necessary changes in `Makefile`, `docker-compose.yml`, and `provision-designer.sh` to make sure portal-designer devstack is continue working with new Dockerfile changes. 
Also Added the missing `docker_gunicorn_configuration.py` file https://github.com/edx/portal-designer/pull/197/files#diff-71ef47849e3310ce9993b031e3a994e104ee98574b207b6a83d3f30c15314533 
I've followed the instructions in this [Guide](https://github.com/edx/portal-designer/blob/master/docs/getting_started.rst) to test portal designer with devstack.

build: update Dockerfile for portal designer k8s deployment and add missing `docker_gunicorn_configuration.py`(PSRE-1847)

---

.github/workflows/upgrade-python-requirements.yml

Updates the cron job for python requirements updates to always check on Tuesdays.

feat: update python updates cron job

---

.github/workflows/ci.yml
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

Reverts edx/portal-designer#225

Revert "fix: remove deprecated codecov dependency"

---

.github/workflows/ci.yml
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

Reverts edx/portal-designer#226

Revert "Revert "fix: remove deprecated codecov dependency""
