designer/apps/core/__init__.py, designer/apps/core/apps.py, designer/apps/core/signals.py, designer/apps/core/tests/test_signals.py
When a user with staff logs in for the first time, they used to just see the word "unauthorized" on a blank page. Now, they will automatically be added to Observers, and see a blank CMS instead.
Users who have already tried to log into wagtail will **not** be added to the group automatically.
=> Add staff users to Observer group on first login

designer/urls.py
Since adding things to the wagtail CMS is easy, but removing things is
hard, the quickest removal of the duplicate site creation page is to
redirect the generic one to the custom one.
=> Redirect Add A Site link to site creation mgmt cmd

designer/apps/pages/models.py, designer/apps/pages/tests/test_create_pages.py, designer/apps/pages/utils.py
This PR prevents a site (`IndexPage`) from having both `EnterprisePage` and `ProgramPage` as children pages. Additionally, a site (`IndexPage`) is limited to a single `EnterprisePage` as a child page.
This approach prevents the appropriate type of page from being selected when clicking the "Add Child Page" button in the CMS. In an `IndexPage` already has a `ProgramPage` child, clicking "Add Child Page" will bring the user directly to the `ProgramPage` creation, as opposed to a page that allows the user to select `ProgramPage` or `EnterprisePage`.
Note: In `test_create_pages.py`, I moved the `_create_program_page_data` and `_create_enterprise_page_data` methods into `PageCreationMixin` so that both `ProgramPageCreationTests` and `EnterprisePageCreationTests` have access to those methods to …
=> Prevent child pages from being created if there is a mismatch in sibling page types

designer/apps/api/urls.py
[BOM-1336](https://openedx.atlassian.net/browse/BOM-1336)
- One instance of warning will be removed by django upgrade to 2.0, as it is coming from django code
- Remaining URL warnings will be fixed by wagtail update.
=> BOM-1336: Fixed url configuration

.annotation_safe_list.yml, .travis.yml, Makefile, designer/settings/base.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/django.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, tox.ini
**Ticket:** [BOM-1402](https://openedx.atlassian.net/browse/BOM-1402)
- Dropped support for Django1.11
- Added test support for Django2.2 in Travis
- Upgraded `wagtail` to 2.7.1
=> BOM-1402 Dropped support for Django1.11

designer/apps/core/apps.py, designer/urls.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/django.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.in, requirements/quality.txt, requirements/test.in, requirements/test.txt
https://github.com/edx/portal-designer/pull/97 removed the pin for edx-lint in test.in, but bumped it to the most recent version in quality.in, which resulted in make upgrade being unable to resolve versions once it upgraded again. 
removing the pin in quaility.in seems to fix things
=> Update portal-designer requirements

.travis.yml
[MST-388](https://openedx.atlassian.net/browse/MST-388)
Updated to use Focal 20.04 rather than the default OS environment (16.04), tested build locally.
=> Update build to use Ubuntu Focal 20.04

designer/apps/api/v1/views.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/django.txt, requirements/doc.txt, requirements/github.in, requirements/pip-tools.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt
The bug mentioned on [ARCHBOM-1078](https://openedx.atlassian.net/browse/ARCHBOM-1078) is fixed in `social-auth-core==3.3.3`, See [this comment](https://openedx.atlassian.net/browse/BOM-2094?focusedCommentId=514498) for details, now we are unpinning it wherever it was previously pinned due to that bug.
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2189
=> BOM-2189 : Unpin social-auth-core

requirements/constraints.txt
Requirements upgrade is failing because greater versions of wagtail are incompatible with Django 2.x
=> fix: pin wagtail to 2.13.4

designer/settings/base.py
**Issue:** [BOM-2782](https://openedx.atlassian.net/browse/BOM-2782)
- Added the `DeploymentMonitroringMiddleware` to record `Django` and `Python` versions in the `NewRelic`.
=> BOM-2782: Use DeploymentMonitoringMiddleware in settings

.annotation_safe_list.yml, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt
wagtail pin was for django 2.2 which we no longer support.
Upgrading wagtail meant we had to update the PII annotations a bit.
diff_cover was dealing with an unfortunate version pin in its own dependencies which is now gone
=> remove no longer needed constraints

Makefile
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this [PR](https://github.com/openedx/edx-repo-health/pull/271) for new check added in edx-repo-health. 
JIRA: https://2u-internal.atlassian.net/browse/BOM-3426
=> fix: Install pip and pip-tools after upgrading

designer/settings/base.py
**Issue:** [BOM-3449](https://2u-internal.atlassian.net/browse/BOM-3449)
- Add `CookieMonitoringMiddleware` in settings.
=> build: add cookie monitoring middleware

designer/apps/branding/tests/utils.py, designer/apps/core/tests/utils.py, designer/apps/pages/tests/utils.py
This [Python Requirements Update](https://github.com/edx/portal-designer/pull/206) is failing a quality check due to ambiguous variables. This PR updates the variables to fix the quality check:
The error: 
`E741 ambiguous variable name 'l'`
Here's [more info on the error](https://www.flake8rules.com/rules/E741.html#:~:text=Variables%20named%20I%20%2C%20O%20%2C%20and,variables%20to%20something%20more%20descriptive.).
=> style: change lambda variables for quality

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt
The Python requirements action was failing due to an older version of pip-tools. I manually updated the version of that package, installed it, and then was able to run `make upgrade` successfully.
=> chore: upgrade requirements

requirements/production.in, requirements/production.txt
- Under the issue https://github.com/edx/portal-designer/issues/253, adding the `pymemcache` dependency in requirements to prepare for cache backend migration.
=> build: add pymemcache dependency

designer/settings/devstack.py
- Under the issue https://github.com/edx/portal-designer/issues/253, migrating the devstack cache backend from `MemcachedCache` to `PyMemcacheCache`. 
- devstack cache is not being used right now, but still updating the configuration to keep the standard same with all the other IDAs.
=> build: migrate devstack cache backend

designer/settings/devstack.py
- The parameter needs to be `ignore_exc` instead of `ignore_exec` for cache backend options.
=> fix: fix the cache backend options parameter

.github/workflows/ci.yml, designer/apps/api/urls.py, designer/apps/core/__init__.py, designer/apps/core/admin.py, designer/urls.py, tox.ini
Adding django42 support only.
- codemod used
- [modernize_tox_django42](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/tox_moderniser_django42.py)
- [modernize_github_actions_django42](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/github_actions_modernizer_django42.py)
- [remove_providing_args](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/remove_providing_args_arg.py)
- [django-upgrade](https://github.com/adamchainz/django-upgrade)
- Resolves https://github.com/edx/portal-designer/issues/251
=> [Django 4.2]: Fix: Add support for Django 4.2

designer/settings/base.py
Remove unused JWT_AUTH_REFRESH_COOKIE setting. This setting was never actually used, so there is no timing issues.
See DEPR for details:
https://github.com/openedx/public-engineering/issues/190
=> fix: remove JWT_AUTH_REFRESH_COOKIE

requirements/dev.in
pip tools and [this constraint](https://github.com/openedx/edx-lint/pull/406) will conflict. Normally not an issue since the constraint doesn't apply to pip-tools.in but because we have dev depend on pip-tools in this repo the dev requirements are unable to compile (https://github.com/edx/portal-designer/actions/runs/8394856396/job/22992880471)
We should be able to run the requirements job again once this is merged
=> feat: remove piptools from dev deps

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt
**Jira**: [COSMO-255](https://2u-internal.atlassian.net/browse/COSMO-255) (private)
This pull request reverts the following two commits.
* d91d943c1b6fae15274e1a8fb24252c0325068a8
* e8883bdbfb271cbf1810b8b5eced7723233be16d
Starting 04/05/2024, deployments of this service started to fail due to failing migrations on the wagtail core model in the wagtail application. We are reverting the code changes up until the issue began to rule out an issue in any of our Python requirements upgrade, namely the upgrade of wagtail from `6.0.1` to `6.0.2`.
=> Revert Python requirements upgrades.

.github/workflows/mysql8-migrations-check.yml
The latest version of `python-xmlsec` is breaking the `mysql8-migrations` Github action. See [issue #314](https://github.com/xmlsec/python-xmlsec/issues/314).
The recommended course of action is to pin the version of `python-xmlsec` in the action.
=> Fix broken mysql8-migrations-check workflow due to python-xmlsec.

.coveragerc, .github/workflows/ci.yml
**JIRA:** [COSMO-267](https://2u-internal.atlassian.net/browse/COSMO-267?atlOrigin=eyJpIjoiM2Y3YjExN2ZkMGRiNDQ3Nzk2OGFjNzUxOTYxMzA3NWIiLCJwIjoiaiJ9)
**Description:** Replaces the use of codecov with python-coverage-comment, which is the tool used in other private repositories.
=> build: replace codecov

.github/workflows/mysql8-migrations-check.yml
- `set-output` has been deprecated by GitHub and it is suggested to be replaced by GitHub.
=> fix: replace deprecated set-output

.github/workflows/ci.yml, requirements/base.in, requirements/base.txt, requirements/common_constraints.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, tox.ini
=> Adding python3.12 support.

designer/settings/base.py
Portal designer is missing two middleware classes that enable custom spans in Datadog.
=> fix: add middleware for datadog

designer/settings/utils.py
Ticket: https://2u-internal.atlassian.net/browse/COSMO-593
This PR modifies the logging configuration to align with the Datadog Python pipeline standards.
Adjusting logging format to ensure they are compatible with Datadog’s ingestion requirements.
Sets Django request logs to the INFO level to maintain optimal log verbosity and clarity.
=> chore: Refactor logging format for Datadog pipeline integration
